<?php

/**
 * ReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Report');
    }

    public function getTargetDateReports($targetDate) {
      $query = Doctrine_Core::getTable('Report')
        ->createQuery('r')
        ->innerJoin('r.User u')
        ->where('r.updated_at BETWEEN ? AND ?', array(date('Y-m-d 00:00:00', strtotime($targetDate)), date('Y-m-d 23:59:59', strtotime($targetDate))));

      return $query->execute();
    }
}