generator:
  class: sfDoctrineGenerator
  param:
    model_class:           User
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:      [id, first_name, last_name, email]
        max_per_page: 5
      filter:  ~
      form:
        class:  UserForm
      edit:    ~
      new:     ~
